version: '3.7'

services:
  database:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - mad
    volumes:
      - dbdata:/var/lib/mysql
  backend:
    build: ../backend
    container_name: backend
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - mad
    expose:
      - 9000

  frontend:
    build: ../frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - mad
    expose:
      - 80

  adminer:
    image: adminer
    restart: always
    networks:
      - mad
    ports:
      - 8081:8080

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - mad
    ports:
      - "80:80"

networks:
  mad:


volumes:
  dbdata:
