version: '3.7'

services:
  backend:
    build: ../backend
    container_name: backend
    restart: always
    depends_on:
      - database
    networks:
      - mad
    ports:
      - "8080:8080"

  frontend:
    build: ../frontend
    container_name: frontend
    restart: always
    networks:
      - mad
    ports:
      - "80:80"

  database:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - mad

  adminer:
    image: adminer
    restart: always
    networks:
      - mad
    ports:
      - 8081:8080
networks:
  mad:
